export default [
  { path: '/user', layout: false, routes: [{ path: '/user/login', component: './User/Login' }] },
  { path: '/home', icon: 'HomeOutlined', component: './Home', name: '主页' },
  { path: '/question', icon: 'BarsOutlined', component: './Question', name: '题库' },
  {
    path: '/question/:id',
    component: './Question/DoOnline',
    name: '在线做题',
    layout: false,
    props: true,
  },
  { path: '/inventory', icon: 'GroupOutlined', component: './QuestionInventory', name: '题单' },
  { path: '/submission', icon: 'AuditOutlined', component: './Submission', name: '提交' },
  { path: '/contests', icon: 'RiseOutlined', component: './Contests', name: '比赛' },
  {
    path: '/rating',
    icon: 'TrophyOutlined',
    name: '排行榜',
    routes: [
      { path: '/rating', redirect: '/rating/acm' },
      {
        path: '/rating/acm',
        icon: 'TrophyFilled',
        component: './Rating/Acm',
        name: 'ACM 排行榜',
      },
      { path: '/rating/io', icon: 'TrophyOutlined', component: './Rating/Io', name: 'IO 排行榜' },
    ],
  },
  {
    path: '/community',
    icon: 'CommentOutlined',
    component: './Community',
    name: '交流',
    routes: [
      { path: '/community', redirect: '/community/questions' },
      {
        path: '/community/questions',
        component: './Community/Questions',
        name: '题目交流',
        hideInMenu: true,
      },
      {
        path: '/community/skills',
        component: './Community/Skills',
        name: '技术交流',
        hideInMenu: true,
      },
      {
        path: '/community/learn',
        component: './Community/Learn',
        name: '学习分享',
        hideInMenu: true,
      },
      {
        path: '/community/help',
        component: './Community/Help',
        name: '求助',
        hideInMenu: true,
      },
      {
        path: '/community/feedback',
        component: './Community/Feedback',
        name: '意见反馈',
        hideInMenu: true,
      },
      {
        path: '/community/other',
        component: './Community/Other',
        name: '其他',
        hideInMenu: true,
      },
      {
        path: '/community/thumb',
        component: './Community/Thumb',
        name: '点赞',
        hideInMenu: true,
      },
      {
        path: '/community/favour',
        component: './Community/Favour',
        name: '收藏',
        hideInMenu: true,
      },
      {
        path: '/community/my',
        component: './Community/My',
        name: '我的',
        hideInMenu: true,
      },
      {
        path: '/community/subscriptions',
        component: './Community/Subscriptions',
        name: '订阅',
        hideInMenu: true,
      },
    ],
  },
  {
    path: '/repository',
    icon: 'InboxOutlined',
    name: '资源',
    routes: [
      { path: '/repository', redirect: '/repository/video' },
      {
        path: '/repository/video',
        icon: 'VideoCameraOutlined',
        component: './Repository/Video',
        name: '视频',
      },
      {
        path: '/repository/doc',
        icon: 'FileWordOutlined',
        component: './Repository/Doc',
        name: '文档',
      },
      {
        path: '/repository/wiki',
        icon: 'ReadOutlined',
        component: './Repository/Wiki',
        name: 'Wiki',
      },
    ],
  },
  {
    path: '/market',
    icon: 'ShopOutlined',
    component: './Market',
    name: '集市',
    layout: false,
  },
  {
    path: '/toolkit',
    icon: 'ToolOutlined',
    name: '工具',
    routes: [
      {
        path: '/toolkit/data-generator',
        component: './Toolkit/DataGenerator',
        name: '数据生成器',
        hideInMenu: true,
      },
      {
        path: 'https://yocy.top',
        component: './Toolkit/ProblemHelper',
        name: '出题助手',
        hideInMenu: true,
      },
      {
        path: 'https://yuanmlin.yoww.cn',
        component: './Toolkit/CodeMaker',
        name: '代码生成工作台',
        hideInMenu: true,
      },
    ],
  },
  {
    path: '/about',
    icon: 'InfoCircleOutlined',
    name: '关于',
    routes: [
      { path: '/about', redirect: '/about/site' },
      { path: '/about/site', component: './About/Site', name: '站点简介' },
      { path: '/about/faq', component: './About/Faq', name: 'FAQ' },
      { path: '/about/course', component: './About/Course', name: '发展历程' },
    ],
  },
  {
    path: '/admin',
    layout: false,
    icon: 'crown',
    name: '管理页',
    access: 'canAdmin',
    component: '@/layouts/admin',
    routes: [
      { path: '/admin', redirect: '/admin/user' },
      { icon: 'table', path: '/admin/user', component: './Admin/User', name: '用户管理' },
    ],
  },
  { path: '/', redirect: '/home' },
  { path: '*', layout: false, component: './404' },
];
